# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

os:
  - linux
language: cpp
compiler:
  - gcc
#  - clang
#  We should test with clang within the modules, not here.
script: ./travis.sh
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - time
#    - gcc-4.8
#    - g++-4.8
#    - clang
#   - libxqilla-dev # missing, but not needed?
#env:
#  matrix:
#    - SHARED_LIB=ON  STATIC_LIB=ON CMAKE_PKG=ON  BUILD_TYPE=release VERBOSE_MAKE=false
#    - SHARED_LIB=OFF STATIC_LIB=ON CMAKE_PKG=OFF BUILD_TYPE=debug   VERBOSE_MAKE=true VERBOSE
notifications:
  email: false
sudo: false


# Copied from https://github.com/nim-lang/Nim/wiki/TravisCI
#language: c
env:
  # Build and test against the master and/or devel branches of Nim
  - BRANCH=master
  #- BRANCH=devel
  #- BRANCH=v0.18.0
compiler:
  # Build and test using both gcc and clang
  - gcc
  #- clang
#matrix:
#  allow_failures:
#    # Ignore failures when building against the devel Nim branch
#    - env: BRANCH=devel
#  fast_finish: true
install:
  - |
    if [ ! -x nim-$BRANCH/bin/nim ]; then
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
      cd nim-$BRANCH
      git clone --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      cd nim-$BRANCH
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    cd ..
before_script:
    - export PATH="$(pwd)/nim-$BRANCH/bin${PATH:+:$PATH}"
#script:
#    # Replace uppercase strings!
#    - nim c --cc:$CC --verbosity:0 -r MYFILE.nim
#    # Optional: build docs.
#    - nim doc --docSeeSrcUrl:https://github.com/AUTHOR/MYPROJECT/blob/master --project MYFILE.nim
cache:
  directories:
    - nim-master
    #- nim-devel
branches:
  except:
    - gh-pages
